welcome:
  type: get
  pattern: /
  controler: main
  action: index

api_test:
  type: get
  pattern: /api/test
  controler: api
  action: test

any_get:
  type: get
  pattern: /{any}
  controler: main
  action: index
  requirements:
    any: ".+"

any_post:
  type: post
  pattern: /{any}
  controler: main
  action: index
  requirements:
    any: ".+"